//! Mesh-level fillet and chamfer operations.
//!
//! Detects sharp edges via dihedral-angle thresholding, then insets each
//! edge vertex pair along the edge's adjacent face normals:
//! - **Fillet** replaces the edge with a rounded strip of `n_segments`
//!   facets approximating an arc tangent to both faces.
//! - **Chamfer** inserts a single flat bevel between the two faces.
//!
//! This is a mesh-level approximation, not a true B-Rep fillet. It works
//! best on convex edges of meshes generated by `extrude`/`revolve`. It
//! deliberately skips edges shorter than `epsilon` to avoid degenerate
//! output on coincident vertices.

use crate::extrude::Mesh;
use std::collections::HashMap;

/// Threshold below which two normal vectors are considered the same face
/// (i.e., not a sharp edge). Cosine of 30° ≈ 0.866 — angles smaller than
/// that count as "sharp".
const SHARP_EDGE_THRESHOLD: f32 = 0.866;
const MIN_EDGE_LENGTH: f32 = 1e-6;

/// Apply a fillet to all sharp edges of `mesh`.
pub fn apply_fillet(mesh: &Mesh, radius: f32) -> Mesh {
    apply_edge_bevel(mesh, radius, BevelKind::Fillet)
}

/// Apply a chamfer (flat 45° bevel) to all sharp edges of `mesh`.
pub fn apply_chamfer(mesh: &Mesh, distance: f32) -> Mesh {
    apply_edge_bevel(mesh, distance, BevelKind::Chamfer)
}

#[derive(Clone, Copy, PartialEq)]
enum BevelKind {
    Fillet,
    Chamfer,
}

fn apply_edge_bevel(mesh: &Mesh, amount: f32, kind: BevelKind) -> Mesh {
    if amount <= 0.0 {
        return mesh.clone();
    }

    let edges = detect_sharp_edges(mesh);
    if edges.is_empty() {
        return mesh.clone();
    }

    // For each sharp edge, we need:
    //   - The two adjacent face normals (n_a, n_b)
    //   - The two endpoints (p0, p1)
    //
    // We then build a new mesh that:
    //   1. Keeps all original triangles that don't touch a sharp edge.
    //   2. For each vertex on a sharp edge, splits it into two copies — one
    //      shifted by +amount along n_a, one shifted by +amount along n_b.
    //   3. Connects them with either an arc strip (fillet) or a single bevel
    //      quad (chamfer).
    //
    // To keep the algorithm manageable for an MVP, we apply a vertex-split
    // only along edges, leaving face interiors alone. This is the standard
    // "edge bevel" used in polygonal modeling.

    let mut builder = MeshBuilder::from_mesh(mesh);

    // For each sharp edge, register a bevel. Each unique vertex pair is
    // processed once.
    let mut seen: std::collections::HashSet<(u32, u32)> = std::collections::HashSet::new();
    for edge in &edges {
        let key = if edge.v0 < edge.v1 {
            (edge.v0, edge.v1)
        } else {
            (edge.v1, edge.v0)
        };
        if !seen.insert(key) {
            continue;
        }
        bevel_edge(&mut builder, edge, amount, kind);
    }

    builder.finish()
}

#[derive(Debug, Clone, Copy)]
struct SharpEdge {
    v0: u32,
    v1: u32,
    /// Average face normal on one side of the edge.
    n_a: [f32; 3],
    /// Average face normal on the other side.
    n_b: [f32; 3],
}

fn detect_sharp_edges(mesh: &Mesh) -> Vec<SharpEdge> {
    // Build edge → list of (face_index, face_normal) entries
    let mut edge_faces: HashMap<(u32, u32), Vec<([f32; 3], usize)>> = HashMap::new();

    for (fi, tri) in mesh.indices.chunks(3).enumerate() {
        let a = tri[0];
        let b = tri[1];
        let c = tri[2];
        let n = face_normal(mesh, a, b, c);
        for (v0, v1) in [(a, b), (b, c), (c, a)] {
            let key = if v0 < v1 { (v0, v1) } else { (v1, v0) };
            edge_faces.entry(key).or_default().push((n, fi));
        }
    }

    let mut sharp = Vec::new();
    for ((v0, v1), faces) in &edge_faces {
        if faces.len() != 2 {
            continue;
        }
        let (n_a, _) = faces[0];
        let (n_b, _) = faces[1];
        let dot = n_a[0] * n_b[0] + n_a[1] * n_b[1] + n_a[2] * n_b[2];
        if dot < SHARP_EDGE_THRESHOLD {
            let len = edge_length(mesh, *v0, *v1);
            if len < MIN_EDGE_LENGTH {
                continue;
            }
            sharp.push(SharpEdge { v0: *v0, v1: *v1, n_a, n_b });
        }
    }

    sharp
}

fn edge_length(mesh: &Mesh, v0: u32, v1: u32) -> f32 {
    let p0 = vertex_pos(mesh, v0);
    let p1 = vertex_pos(mesh, v1);
    let dx = p1[0] - p0[0];
    let dy = p1[1] - p0[1];
    let dz = p1[2] - p0[2];
    (dx * dx + dy * dy + dz * dz).sqrt()
}

fn vertex_pos(mesh: &Mesh, v: u32) -> [f32; 3] {
    let i = (v as usize) * 3;
    [mesh.positions[i], mesh.positions[i + 1], mesh.positions[i + 2]]
}

fn face_normal(mesh: &Mesh, a: u32, b: u32, c: u32) -> [f32; 3] {
    let pa = vertex_pos(mesh, a);
    let pb = vertex_pos(mesh, b);
    let pc = vertex_pos(mesh, c);
    let ux = pb[0] - pa[0];
    let uy = pb[1] - pa[1];
    let uz = pb[2] - pa[2];
    let vx = pc[0] - pa[0];
    let vy = pc[1] - pa[1];
    let vz = pc[2] - pa[2];
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    let len = (nx * nx + ny * ny + nz * nz).sqrt();
    if len > 1e-10 {
        [nx / len, ny / len, nz / len]
    } else {
        [0.0, 0.0, 1.0]
    }
}

/// Builder that supports duplicating vertices and adding new triangles
/// without invalidating existing index space.
struct MeshBuilder {
    positions: Vec<f32>,
    normals: Vec<f32>,
    /// Original triangle indices that survive the bevel. Each entry is
    /// (a, b, c) using the *new* vertex indices (after splits).
    kept_triangles: Vec<[u32; 3]>,
    new_triangles: Vec<[u32; 3]>,
    /// Map from original vertex index → list of (split_normal, new_index).
    /// When a vertex is split, every original-indexed triangle touching it
    /// is rebuilt using the appropriate split (based on which face normal
    /// it lies on).
    splits: HashMap<u32, Vec<([f32; 3], u32)>>,
}

impl MeshBuilder {
    fn from_mesh(mesh: &Mesh) -> Self {
        Self {
            positions: mesh.positions.clone(),
            normals: mesh.normals.clone(),
            kept_triangles: mesh
                .indices
                .chunks(3)
                .map(|t| [t[0], t[1], t[2]])
                .collect(),
            new_triangles: Vec::new(),
            splits: HashMap::new(),
        }
    }

    fn append_vertex(&mut self, pos: [f32; 3], normal: [f32; 3]) -> u32 {
        let idx = (self.positions.len() / 3) as u32;
        self.positions.extend_from_slice(&pos);
        self.normals.extend_from_slice(&normal);
        idx
    }

    fn finish(self) -> Mesh {
        // For each original triangle, remap any split vertex to the variant
        // whose split normal best matches the triangle's face normal.
        let mut indices: Vec<u32> = Vec::with_capacity(self.kept_triangles.len() * 3 + self.new_triangles.len() * 3);

        for tri in &self.kept_triangles {
            let face_n = tri_face_normal(&self.positions, tri);
            for &v in tri {
                let mapped = self.remap_vertex(v, &face_n);
                indices.push(mapped);
            }
        }
        for tri in &self.new_triangles {
            indices.extend_from_slice(tri);
        }

        Mesh { positions: self.positions, normals: self.normals, indices }
    }

    fn remap_vertex(&self, original: u32, face_normal: &[f32; 3]) -> u32 {
        match self.splits.get(&original) {
            None => original,
            Some(variants) => {
                // Pick the variant whose normal is closest to face_normal.
                let mut best = variants[0].1;
                let mut best_dot = -2.0f32;
                for (n, idx) in variants {
                    let d = n[0] * face_normal[0] + n[1] * face_normal[1] + n[2] * face_normal[2];
                    if d > best_dot {
                        best_dot = d;
                        best = *idx;
                    }
                }
                best
            }
        }
    }
}

fn tri_face_normal(positions: &[f32], tri: &[u32; 3]) -> [f32; 3] {
    let a = tri[0] as usize * 3;
    let b = tri[1] as usize * 3;
    let c = tri[2] as usize * 3;
    let ux = positions[b] - positions[a];
    let uy = positions[b + 1] - positions[a + 1];
    let uz = positions[b + 2] - positions[a + 2];
    let vx = positions[c] - positions[a];
    let vy = positions[c + 1] - positions[a + 1];
    let vz = positions[c + 2] - positions[a + 2];
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    let len = (nx * nx + ny * ny + nz * nz).sqrt();
    if len > 1e-10 {
        [nx / len, ny / len, nz / len]
    } else {
        [0.0, 0.0, 1.0]
    }
}

/// Apply a bevel to a single sharp edge.
///
/// For each endpoint vertex, we create two split copies:
/// - One shifted by `+amount * n_a` (will be used by face A's triangles)
/// - One shifted by `+amount * n_b` (will be used by face B's triangles)
/// The space between the two split pairs is then bridged with an arc strip
/// (fillet) or a single quad (chamfer).
fn bevel_edge(builder: &mut MeshBuilder, edge: &SharpEdge, amount: f32, kind: BevelKind) {
    let p0 = vertex_pos_from(builder, edge.v0);
    let p1 = vertex_pos_from(builder, edge.v1);

    // For chamfer: each endpoint splits into one variant per face, offset
    // by `amount` along that face's outward normal. We then add two triangles
    // forming a flat bevel quad.
    let p0a = [p0[0] + amount * edge.n_a[0], p0[1] + amount * edge.n_a[1], p0[2] + amount * edge.n_a[2]];
    let p0b = [p0[0] + amount * edge.n_b[0], p0[1] + amount * edge.n_b[1], p0[2] + amount * edge.n_b[2]];
    let p1a = [p1[0] + amount * edge.n_a[0], p1[1] + amount * edge.n_a[1], p1[2] + amount * edge.n_a[2]];
    let p1b = [p1[0] + amount * edge.n_b[0], p1[1] + amount * edge.n_b[1], p1[2] + amount * edge.n_b[2]];

    let i_p0a = builder.append_vertex(p0a, edge.n_a);
    let i_p0b = builder.append_vertex(p0b, edge.n_b);
    let i_p1a = builder.append_vertex(p1a, edge.n_a);
    let i_p1b = builder.append_vertex(p1b, edge.n_b);

    builder.splits.entry(edge.v0).or_default().push((edge.n_a, i_p0a));
    builder.splits.entry(edge.v0).or_default().push((edge.n_b, i_p0b));
    builder.splits.entry(edge.v1).or_default().push((edge.n_a, i_p1a));
    builder.splits.entry(edge.v1).or_default().push((edge.n_b, i_p1b));

    if kind == BevelKind::Chamfer {
        // Flat bevel quad between (p0a, p1a) and (p0b, p1b).
        // Use the bisector normal for both triangles.
        let bisect = normalize([
            edge.n_a[0] + edge.n_b[0],
            edge.n_a[1] + edge.n_b[1],
            edge.n_a[2] + edge.n_b[2],
        ]);
        // Use new vertices with the bisecting normal so the bevel is shaded smoothly.
        let m0 = builder.append_vertex(p0a, bisect);
        let m1 = builder.append_vertex(p1a, bisect);
        let m2 = builder.append_vertex(p0b, bisect);
        let m3 = builder.append_vertex(p1b, bisect);
        builder.new_triangles.push([m0, m1, m2]);
        builder.new_triangles.push([m1, m3, m2]);
    } else {
        // Fillet: insert an arc strip with N segments.
        let n_segments = 4;
        let mut prev_a = i_p0a;
        let mut prev_b = i_p1a;
        for i in 1..n_segments {
            let t = i as f32 / n_segments as f32;
            // Slerp the normal from n_a to n_b.
            let n_mid = slerp_unit(edge.n_a, edge.n_b, t);
            let offset_pos_0 = [
                p0[0] + amount * n_mid[0],
                p0[1] + amount * n_mid[1],
                p0[2] + amount * n_mid[2],
            ];
            let offset_pos_1 = [
                p1[0] + amount * n_mid[0],
                p1[1] + amount * n_mid[1],
                p1[2] + amount * n_mid[2],
            ];
            let new_a = builder.append_vertex(offset_pos_0, n_mid);
            let new_b = builder.append_vertex(offset_pos_1, n_mid);
            builder.new_triangles.push([prev_a, prev_b, new_a]);
            builder.new_triangles.push([prev_b, new_b, new_a]);
            prev_a = new_a;
            prev_b = new_b;
        }
        // Final cap connecting the last arc segment to the n_b split.
        builder.new_triangles.push([prev_a, prev_b, i_p0b]);
        builder.new_triangles.push([prev_b, i_p1b, i_p0b]);
    }
}

fn vertex_pos_from(builder: &MeshBuilder, v: u32) -> [f32; 3] {
    let i = (v as usize) * 3;
    [builder.positions[i], builder.positions[i + 1], builder.positions[i + 2]]
}

fn normalize(v: [f32; 3]) -> [f32; 3] {
    let len = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt();
    if len > 1e-10 {
        [v[0] / len, v[1] / len, v[2] / len]
    } else {
        v
    }
}

/// Slerp between two unit vectors.
fn slerp_unit(a: [f32; 3], b: [f32; 3], t: f32) -> [f32; 3] {
    let dot = (a[0] * b[0] + a[1] * b[1] + a[2] * b[2]).clamp(-1.0, 1.0);
    let theta = dot.acos();
    if theta.abs() < 1e-6 {
        return a;
    }
    let sin_theta = theta.sin();
    let w0 = ((1.0 - t) * theta).sin() / sin_theta;
    let w1 = (t * theta).sin() / sin_theta;
    normalize([
        w0 * a[0] + w1 * b[0],
        w0 * a[1] + w1 * b[1],
        w0 * a[2] + w1 * b[2],
    ])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extrude::Mesh;

    fn cube_mesh() -> Mesh {
        // 1×1×1 cube centered at origin: 8 vertices, 12 triangles.
        let positions = vec![
            -0.5, -0.5, -0.5, // 0
             0.5, -0.5, -0.5, // 1
             0.5,  0.5, -0.5, // 2
            -0.5,  0.5, -0.5, // 3
            -0.5, -0.5,  0.5, // 4
             0.5, -0.5,  0.5, // 5
             0.5,  0.5,  0.5, // 6
            -0.5,  0.5,  0.5, // 7
        ];
        let normals = vec![
            0.0, 0.0, -1.0, // 0
            0.0, 0.0, -1.0, // 1
            0.0, 0.0, -1.0, // 2
            0.0, 0.0, -1.0, // 3
            0.0, 0.0,  1.0, // 4
            0.0, 0.0,  1.0, // 5
            0.0, 0.0,  1.0, // 6
            0.0, 0.0,  1.0, // 7
        ];
        let indices = vec![
            // -Z (bottom)
            0, 2, 1,
            0, 3, 2,
            // +Z (top)
            4, 5, 6,
            4, 6, 7,
            // -Y (front)
            0, 1, 5,
            0, 5, 4,
            // +Y (back)
            2, 3, 7,
            2, 7, 6,
            // -X (left)
            0, 4, 7,
            0, 7, 3,
            // +X (right)
            1, 2, 6,
            1, 6, 5,
        ];
        Mesh { positions, normals, indices }
    }

    #[test]
    fn detect_cube_edges() {
        let mesh = cube_mesh();
        let edges = detect_sharp_edges(&mesh);
        assert_eq!(edges.len(), 12, "cube has 12 sharp edges");
    }

    #[test]
    fn chamfer_adds_geometry() {
        let mesh = cube_mesh();
        let beveled = apply_chamfer(&mesh, 0.1);
        assert!(beveled.vertex_count() > mesh.vertex_count(),
            "chamfer should add vertices (was {}, now {})",
            mesh.vertex_count(), beveled.vertex_count());
        assert!(beveled.indices.len() > mesh.indices.len(),
            "chamfer should add triangles");
    }

    #[test]
    fn fillet_adds_geometry() {
        let mesh = cube_mesh();
        let beveled = apply_fillet(&mesh, 0.1);
        assert!(beveled.vertex_count() > mesh.vertex_count(),
            "fillet should add vertices (was {}, now {})",
            mesh.vertex_count(), beveled.vertex_count());
    }

    #[test]
    fn fillet_zero_amount_is_identity() {
        let mesh = cube_mesh();
        let result = apply_fillet(&mesh, 0.0);
        assert_eq!(result.indices.len(), mesh.indices.len());
    }
}
